name: main-workflow

on:
  workflow_dispatch:
    inputs:
      framework:
        description: "Framework name"

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      framework: ${{ inputs.framework }}
