name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      framework:
        description: Framework name
        required: true

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      framework: ${{ inputs.framework }}
