name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Reusable Workflow
        uses: ./reusable.yml # Path to the reusable workflow file
