name: My Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Message
        run: echo "This is the reusable workflow."
